_wandb:
    value:
        cli_version: 0.25.1
        e:
            0d9r8t5g01vthycaau0bvu1jgtzb5uxa:
                codePath: ..\..\Deep Learning\Code\Code-20260407\wandb_test.py
                codePathLocal: ..\..\Deep Learning\Code\Code-20260407\wandb_test.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "468738969600"
                        used: "286222929920"
                email: buetzjul@students.zhaw.ch
                executable: C:\Users\Julian\miniconda3\envs\torchfix\python.exe
                git:
                    commit: 8f0630064da30e6c14150b0526ad4cb2eb9c1fdb
                    remote: https://github.com/julbue/msls-co4-ss26.git
                host: DESKTOP-JAI8NTM
                memory:
                    total: "16860798976"
                os: Windows-10-10.0.22621-SP0
                program: c:\Studium\Master\2. Semester\Deep Learning\Code\Code-20260407\wandb_test.py
                python: CPython 3.11.14
                root: C:\Studium\Master\2. Semester\CO4\rep
                startedAt: "2026-04-07T13:26:45.635241Z"
                writerId: 0d9r8t5g01vthycaau0bvu1jgtzb5uxa
        m: []
        python_version: 3.11.14
        t:
            "3":
                - 2
                - 16
            "4": 3.11.14
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
epochs:
    value: 10
lr:
    value: 0.01
